/* R-10's record and the findings over it: what the tree owes the file, what its absence costs, and
   which citation is stale and which suspect. The rule is `docs/requirements/README.md`'s, the digest
   `parse.mjs`'s, and no file is opened here, so a fixture proves each of these. */
import { lineAt } from "../markdown.mjs";
import { KIND, identifiersIn } from "./parse.mjs";
import { revisionFix } from "./citation.mjs";
import { finding } from "./rules.mjs";

/** The record's name inside the tree; `tree.mjs` joins it and nothing else writes it. */
export const RECORD = "digests.json";

const WRITER = "`forge spec check --record`";
const NOTE = `Generated by ${WRITER}, which is the only thing that writes this file. One entry per `
  + "clause of this tree that carries a revision: the revision it is at, and the digest of its "
  + "content there. The rule it serves is R-10 in ./README.md.";
const REPAIR = `Re-record with ${WRITER}, so a spec edit and its digests travel in one commit`;
const ROUTES = (rev) => `Bump the clause's revision, which drops the verdicts that cited revision ${rev}, `
  + `or re-record with ${WRITER}, which clears the suspicion and leaves them standing`;

/** Every clause carrying a revision, in document order. An identifier two documents define is left
 *  out: R-12 is already refusing it, and neither copy is the clause. */
export const entriesOf = (index) => {
  const clauses = {};
  for (const id of index.order) {
    const clause = index.clauses.get(id);
    if (!clause || clause.rev === null || index.duplicates.has(id)) continue;
    clauses[id] = { rev: clause.rev, digest: clause.hash };
  }
  return { note: NOTE, clauses };
};

export const written = (record) => `${JSON.stringify(record, null, 2)}\n`;

const DIGEST = /^[0-9a-f]{64}$/u;

/** The first entry that is not a revision and a digest, or `null`. One that kept its revision and
 *  lost its digest passes coverage and is compared by nothing, so the record is refused on it. */
export const malformedIn = (clauses) => {
  for (const [id, entry] of Object.entries(clauses)) {
    if (!Number.isInteger(entry?.rev) || entry.rev < 0 || !DIGEST.test(entry.digest ?? "")) return id;
  }
  return null;
};

/** One line per entry the write moves, so the writer says what changed rather than that it ran. */
export const movedIn = (held, want) => {
  const before = held ?? {};
  const out = [];
  for (const [id, entry] of Object.entries(want)) {
    if (!before[id]) out.push(`  + ${id} at revision ${entry.rev}`);
    else if (before[id].rev !== entry.rev) out.push(`  ~ ${id} from revision ${before[id].rev} to ${entry.rev}`);
    else if (before[id].digest !== entry.digest) out.push(`  ~ ${id} at revision ${entry.rev}, its words having moved`);
  }
  for (const id of Object.keys(before)) {
    if (!want[id]) out.push(`  - ${id}, which this tree no longer carries`);
  }
  return out;
};

/* Every finding here is about the record rather than a document, because re-recording clears it. */
const coverage = (index, recorded, want) => {
  const out = [];
  for (const [id, entry] of Object.entries(want)) {
    const held = recorded.clauses[id];
    if (!held) {
      out.push(finding(recorded.file, 1, id, "R-10",
        `is a clause at revision ${entry.rev} and this record covers no revision of it. ${REPAIR}`));
    } else if (held.rev !== entry.rev) {
      out.push(finding(recorded.file, 1, id, "R-10",
        `is at revision ${entry.rev} and the digest recorded for it is revision ${held.rev}'s. ${REPAIR}`));
    } else if (held.digest !== entry.digest) {
      out.push(finding(recorded.file, 1, id, "R-10",
        `is at revision ${entry.rev} and the digest recorded for that revision is not this clause's `
        + `words now. ${ROUTES(entry.rev)}`));
    }
  }
  for (const id of Object.keys(recorded.clauses)) {
    if (want[id] || index.duplicates.has(id)) continue;
    out.push(finding(recorded.file, 1, id, "R-10",
      `is recorded here and this tree defines no clause of that identifier. ${REPAIR}`));
  }
  return out;
};

const suspectFix = (id, rev) =>
  `is suspect: ${id} is at revision ${rev} and its words have moved since the digest recorded for `
  + `that revision. ${ROUTES(rev)}`;

/* Deduplicated on the citation and not the identifier: two revisions of one clause are two claims. */
const citationsOf = (text) => {
  const out = new Map();
  for (const one of identifiersIn(text)) {
    if (one.rev === null || !KIND[one.prefix]) continue;
    const written = `${one.id}~${one.rev}`;
    if (!out.has(written)) out.set(written, { ...one, written });
  }
  return [...out.values()];
};

/* Stale is settled by the clause's own revision and no record's, which is why it is asked first and
   why its sentence is `citation.mjs`'s: a third wording of it would be a third answer. */
const citations = (documents, index, recorded) => {
  const out = [];
  for (const { file, text } of documents) {
    for (const one of citationsOf(text)) {
      const clause = index.clauses.get(one.id);
      if (!clause || index.duplicates.has(one.id)) continue;
      const at = () => lineAt(text, text.indexOf(one.written));
      const stale = revisionFix(clause, one);
      if (stale) {
        out.push(finding(file, at(), one.written, "R-10", stale));
        continue;
      }
      const held = recorded.clauses?.[one.id];
      if (!held || held.rev !== one.rev || held.digest === clause.hash) continue;
      out.push(finding(file, at(), one.written, "R-10", suspectFix(one.id, one.rev)));
    }
  }
  return out;
};

const missing = (recorded, want) => (Object.keys(want).length
  ? [finding(recorded.file, 1, RECORD, "R-10",
    `records the digest of every clause of this tree and ${recorded.why}. Write it with ${WRITER}, `
    + "so a citation is judged against the words the clause carried when it was written")]
  : []);

/** R-10 over a tree and the record beside it. A record that is not there is one finding naming the file, and a tree where no clause carries a revision owes no record at all — but the citations are walked either way, since what makes one stale is the clause's own revision, which a tree with no record still has. */
export const recordProblems = ({ documents, index, recorded }) => {
  const want = entriesOf(index).clauses;
  const found = recorded.clauses ? coverage(index, recorded, want) : missing(recorded, want);
  return [...found, ...citations(documents, index, recorded)];
};
