import assert from "node:assert/strict";
import { RuleTester } from "eslint";
import test from "node:test";
import rule from "../src/no-duplicate-comment.js";
import {
  contentWords,
  findOverlaps,
  overlap,
  splitSentences,
  STOP_WORDS,
} from "../src/text-overlap.js";

const tester = new RuleTester({ languageOptions: { ecmaVersion: 2022 } });

const RESTATED = `// The sequence assigns a master-data code whenever the field is left blank, and the
// uniqueness of it is a database constraint rather than application discipline.
const generated = assign();

function later() {
  // Uniqueness of a master-data code is a database constraint, not application discipline,
  // and the sequence assigns one whenever the field arrives blank.
  return generated;
}`;

test("a comment restating an earlier one is reported, at the later of the two", () => {
  tester.run("no-duplicate-comment", rule, {
    valid: [],
    invalid: [
      {
        code: RESTATED,
        errors: [{ messageId: "duplicateComment", line: 6 }],
      },
    ],
  });
});

test("comments about different things are left alone, however long", () => {
  tester.run("no-duplicate-comment", rule, {
    valid: [
      {
        code: `// The sequence assigns a master-data code whenever the field is left blank, and its
// uniqueness is a database constraint rather than application discipline.
const a = 1;
// A document that has been posted keeps the values it was posted with; the status moves
// through its own transitions instead of the row being edited into a new shape.
const b = 2;`,
      },
      // Below the length floor on both sides: too little text to mean anything.
      { code: "// same words here\nconst a = 1;\n// same words here\nconst b = 2;" },
      // One comment, however repetitive: a block shares a topic with itself by construction.
      {
        code: `/**
 * The sequence assigns a master-data code whenever the field is left blank.
 * A master-data code is assigned by the sequence whenever the field is blank.
 */
const a = 1;`,
      },
      // A waiver another rule demands per site says the same thing at every site by design.
      {
        code: `// pass-through: keep — route handler: @Get() and the validation pipe carry the work here
function a() { return b(); }
// pass-through: keep — route handler: @Get() and the validation pipe carry the work here
function c() { return d(); }`,
      },
      // This rule's own waiver, over the very text the first case proves is reported.
      {
        code: RESTATED.replace(
          "  // Uniqueness",
          "  // restated: deliberate — the mirror case, and the contrast is why both are written\n  // Uniqueness",
        ),
      },
      // Directives are not prose and never carry a constraint.
      {
        code: `// eslint-disable-next-line no-unused-vars -- the resolver needs the binding present
const a = 1;
// eslint-disable-next-line no-unused-vars -- the resolver needs the binding present
const b = 2;`,
      },
    ],
    invalid: [],
  });
});

test("a waiver without a reason is a marker, and a marker waives nothing", () => {
  tester.run("no-duplicate-comment", rule, {
    valid: [],
    invalid: [
      {
        code: RESTATED.replace("  // Uniqueness", "  // restated: deliberate\n  // Uniqueness"),
        errors: [{ messageId: "duplicateComment" }],
      },
    ],
  });
});

test("the threshold and the floor are a project's to raise", () => {
  tester.run("no-duplicate-comment", rule, {
    valid: [{ code: RESTATED, options: [{ threshold: 0.95 }] }],
    invalid: [
      {
        code: RESTATED,
        options: [{ threshold: 0.2, floor: 3 }],
        errors: [{ messageId: "duplicateComment" }],
      },
    ],
  });
});

test("a report names the line it duplicates, so the fix needs no second reading", () => {
  tester.run("no-duplicate-comment", rule, {
    valid: [],
    invalid: [
      {
        code: RESTATED,
        errors: [
          {
            messageId: "duplicateComment",
            data: {
              line: "1",
              other:
                "The sequence assigns a master-data code whenever the field is left blank, and th…",
            },
          },
        ],
      },
    ],
  });
});

test("the overlap index is symmetric and silent below the floor", () => {
  const a = contentWords("a master-data code is generated by the sequence, never invented");
  const b = contentWords("the sequence generates a master-data code; nobody invents one");
  assert.equal(overlap(a, b, 3), overlap(b, a, 3));
  assert.equal(overlap(a, b, 99), null);
});

test("a stop word carries no weight, and a short sentence is not a sentence", () => {
  assert.equal(STOP_WORDS.has("that"), true);
  assert.equal(contentWords("that this with from").size, 0);
  assert.deepEqual(splitSentences("Too short. Also short."), []);
  assert.equal(splitSentences("x".repeat(40)).length, 1);
});

test("each unordered pair is reported once, worst first", () => {
  const units = [
    ["a", "a master-data code is generated by the sequence and never invented by a caller"],
    ["b", "the sequence generates every master-data code, and no caller ever invents one"],
    ["c", "a posted document keeps the values it carried at the moment it was posted"],
  ];
  const hits = findOverlaps(units, { floor: 3 });
  assert.equal(hits.length, 1);
  assert.deepEqual([hits[0][1][0], hits[0][2][0]].sort(), ["a", "b"]);
});
