#!/usr/bin/env python3
"""Emit the Vietnamese constants of the python vi_cli as ES module source.

The prose in prompts.py is the product. It is generated here rather than retyped so the port
cannot silently reword it; tools/check-vi-parity.mjs then proves the two trees agree.
"""
import ast
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "plugin", "scripts"))
from vi_cli import cta, engine, prompts  # noqa: E402

def lit(value):
    return json.dumps(value, ensure_ascii=False)

def emit(name, value):
    return "export const %s = %s;\n" % (name, lit(value))

out = ["// GENERATED by tools/extract-vi-constants.py — the Vietnamese is copied, never retyped.\n\n"]
for name in ("STYLE", "PLACEHOLDER_RULE", "KEY_CONTEXT", "DOC_KEY_CONTEXT", "UI_CONTEXT",
             "DOC_CONTEXT", "BATCH_TASK", "DOC_TASK", "REVIEW_TASK"):
    out.append(emit(name, getattr(prompts, name)))
out.append(emit("REGISTERS", prompts.REGISTERS))
out.append(emit("REGIONS", prompts.REGIONS))
out.append(emit("GENERIC", cta.GENERIC))
out.append(emit("VI_BARE", sorted(cta.VI_BARE)))

# The glossary block is assembled inside prompts.system_prompt, so its three literals live in that
# function rather than at module level. Same rule as the hints: read them, never repeat them.
prompt_tree = ast.parse(open(prompts.__file__, encoding="utf-8").read())
sp = next(n for n in ast.walk(prompt_tree)
          if isinstance(n, ast.FunctionDef) and n.name == "system_prompt")
glossary_literals = [n.value for n in ast.walk(sp)
                     if isinstance(n, ast.Constant) and isinstance(n.value, str)
                     and any(ord(c) > 127 for c in n.value)]
by_shape = {}
for value in glossary_literals:
    if "\u2192" in value:
        by_shape["GLOSSARY_LINE"] = value
    elif value.rstrip().endswith(":"):
        by_shape["GLOSSARY_HEADER"] = value
    else:
        by_shape["GLOSSARY_KEEP"] = value
for name in ("GLOSSARY_HEADER", "GLOSSARY_LINE", "GLOSSARY_KEEP"):
    if name not in by_shape:
        raise SystemExit("could not find %s in prompts.system_prompt" % name)
    out.append(emit(name, by_shape[name]))

# The two retry hints are built inline in engine._translate_one. Read them out of the AST rather
# than repeating them here: a hand-copied literal is exactly what this script exists to prevent.
tree = ast.parse(open(engine.__file__, encoding="utf-8").read())
fn = next(n for n in ast.walk(tree)
          if isinstance(n, ast.FunctionDef) and n.name == "_translate_one")
vi_literals = [n.value for n in ast.walk(fn)
               if isinstance(n, ast.Constant) and isinstance(n.value, str)
               and any(ord(c) > 127 for c in n.value)]
# Keyed by shape, not by position: ast.walk does not promise source order, and indexing into it
# silently swapped the two the first time.
formatted = [v for v in vi_literals if "%s" in v]
plain = [v for v in vi_literals if "%s" not in v]
if len(formatted) != 1 or len(plain) != 1:
    raise SystemExit("expected one formatted and one plain hint, got %d/%d"
                     % (len(formatted), len(plain)))
out.append(emit("PLACEHOLDER_HINT", formatted[0]))
out.append(emit("BARE_HINT", plain[0]))

open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "plugin", "vi-natural", "vi-text.mjs"), "w",
     encoding="utf-8").writelines(out)
print("wrote plugin/vi-natural/vi-text.mjs")
